import Head from 'next/head';
import { getSession } from 'next-auth/react';
import { NextPageContext } from 'next';
import Navbar from '@/components/Navbar';
import Billboard from '@/components/Billboard';
import MovieList from '@/components/MovieList';
import useMovieList from '@/hooks/useMovieList';
import useFavorites from '@/hooks/useFavorites';
import InfoModal from '@/components/InfoModal';
import useInfoModal from '@/hooks/useInfoModel';
import Feedback from '@/components/Feedback';
import useFeedbackModal from '@/hooks/useFeedbackModal';
import { useRouter } from 'next/router';


export async function getServerSideProps(context: NextPageContext) {
  const session = await getSession(context);
  if (!session) {
    return {
      redirect: {
        destination: '/auth',
        permanent: false,
      }
    }
  }

  return {
    props: {}
  }
}

export default function Home() {
  const { data: movies = [] } = useMovieList();
  const { data: favorites = [] } = useFavorites();
  const { isOpen, closeModal } = useInfoModal();
  const { isFeedOpen, closeFeedModal } = useFeedbackModal();

  const router = useRouter();

    // Access the query parameter (index)
    const index = typeof router.query.index === 'string' ? parseInt(router.query.index, 10) : undefined;


  return (
    <>
      <Head>
        <title>Streamflix - A Netflix Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest"></link>
      </Head>
      <InfoModal visible={isOpen} onClose={closeModal}/>
      <Feedback visible={isFeedOpen} onClose={closeFeedModal} />
      <Navbar index={index}/>
      <Billboard />
      <div className='pb-40 mt-16 sm:mt-2 lg:mt-10 flex flex-col gap-4'>
        <MovieList title='Trending Now' data={movies}/>
        <MovieList title='My List' data={favorites}/>
      </div>
    </>
  )
}
